[workspace]
resolver = "2"
members = [
  "crates/litegis",
  "crates/litegis-so",
]
default-members = [
  "crates/litegis"
]

[workspace.dependencies]
litegis = { path = "crates/litegis" }
rusqlite = { version = "0.38.0" }
