[package]
name = "litegis-so"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "litegis"
crate-type=["cdylib"]

[dependencies]
rusqlite = { workspace = true, features = ["functions", "loadable_extension"] }
litegis = { workspace = true }
